language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

services: mongodb

script: make test

before_deploy:
  - make packages
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/ofelia_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/ofelia_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
